review_logical_access:
    description: Compare system access levels against authorized access matrix
    agent: logical_access_reviewer
    priority: 1
    expected_output: A markdown file containing access-related findings
    output_structure:
        sections:
            - title: Observation 
              requirements:
                - Subject-focused and concise
                - Non-negative phrasing
                - Clear without technical jargon
            - title: Observation Details
              format: bullet_points
              requirements:
                - Direct and concise points that explains the noted discrepancies.
                - Logical flow in main and sub-bullets
                - No background information
                - Clear timeline and scope
                - Evidence-based findings
            - title: Risk Assessment
              components:
                - Identified risks
                - Impact analysis
                - Control gaps
                - System implications
            - title: Risk Rating
              options:
                - Critical
                - High
                - Medium
                - Low
              criteria:
                - Impact severity
                - Likelihood
                - Control effectiveness
            - title: Management Action
              format: bullet_points
              components:
                - Required actions
                - Responsibilities
                - Success criteria
    writing_guidelines:
        style:
            - Use passive voice
            - Avoid personal pronouns
            - No subjective language
            - Plain English
            - Define abbreviations first
        formatting:
            - Consistent bullet point structure
            - Proper comma usage
            - Single transition words
            - Parallel structure in lists
        content:
            - Focus on risk-based observations
            - Clear root cause identification
            - Impact assessment
            - Compensating controls
            - Time frame specification

review_transaction_limits:
    description: Analyze transaction approvals against authorized limits
    agent: limit_reviewer
    priority: 1
    expected_output: A markdown file containing limit-related findings
    output_structure:
        sections:
            - title: Observation Title
              requirements:
                - Subject-focused and concise
                - Non-negative phrasing
                - Clear without technical jargon
            - title: Observation Details
              format: bullet_points
              requirements:
                - Direct and concise points that explains the noted discrepancies.
                - Logical flow in main and sub-bullets
                - No background information
                - Clear timeline and scope
                - Evidence-based findings
            - title: Risk Assessment
              components:
                - Identified risks
                - Impact analysis
                - Control gaps
                - System implications
            - title: Risk Rating
              options:
                - Critical
                - High
                - Medium
                - Low
              criteria:
                - Impact severity
                - Likelihood
                - Control effectiveness
            - title: Management Action
              format: bullet_points
              components:
                - Required actions
                - Timeline
                - Responsibilities
                - Success criteria
    writing_guidelines:
        style:
            - Use passive voice
            - Avoid personal pronouns
            - No subjective language
            - Plain English
            - Define abbreviations first
        formatting:
            - Consistent bullet point structure
            - Proper comma usage
            - Single transition words
            - Parallel structure in lists
        content:
            - Focus on risk-based observations
            - Clear root cause identification
            - Impact assessment
            - Compensating controls
            - Time frame specification


review_transactions:
    description: Analyze transactions for policy violations
    agent: transaction_reviewer
    priority: 1
    expected_output: A markdown file containing transaction-related findings with title, background, discrepancies, and user feedback section












review_audit_trail:
  description: Verify change management compliance and identify potential process violations
  agent: audit_trail_reviewer
  priority: 1
  expected_output: A markdown file containing change management audit findings
  output_structure:
    sections:
      - title: Observation
        requirements:
          - Subject-focused and concise
          - Non-negative phrasing
          - Clear without technical jargon

      - title: Observation Details
        format: bullet_points
        requirements:
          - Direct and concise points explaining change management discrepancies
          - Logical flow in main and sub-bullets
          - No background information
          - Clear timeline and scope
          - Evidence-based findings

      - title: Risk Assessment
        components:
          - Identified risks in change management process
          - Impact analysis of non-compliant changes
          - Control gaps in change execution
          - System and operational implications

      - title: Risk Rating
        options:
          - Critical
          - High
          - Medium
          - Low
        criteria:
          - Change management SLA violation severity
          - Unauthorized user access likelihood
          - Control effectiveness
          - Potential system impact

      - title: Management Action
        format: bullet_points
        components:
          - Required corrective actions
          - User responsibility assignments
          - Success criteria for process improvement

  writing_guidelines:
    style:
      - Use passive voice
      - Avoid personal pronouns
      - No subjective language
      - Plain English
      - Define abbreviations first

    formatting:
      - Consistent bullet point structure
      - Proper comma usage
      - Single transition words
      - Parallel structure in lists

    content:
      - Focus on change management process risks
      - Clear root cause identification
      - Impact assessment of non-compliant changes
      - Recommended compensating controls
      - Specific time frame specification



review_transaction_policy:
  description: Verify transactions are inline with the policy and provide comprehensive analysis of compliance status.
  agent: transaction_reviewer
  priority: 1
  expected_output: A markdown file containing transaction policy compliance findings
  output_structure:
    sections:
      - title: Observation
        requirements:
          - Subject-focused and concise
          - Non-negative phrasing
          - Clear without technical jargon

      - title: Observation Details
        format: bullet_points
        requirements:
          - Direct and concise points explaining transactions non compliance discrepancies
          - Logical flow in main and sub-bullets
          - No background information
          - Clear timeline and scope
          - Evidence-based findings

      - title: Risk Assessment
        components:
          - Identified risks in transactions non compliance process
          - Impact analysis of non-compliant transactions non compliance
          - Control gaps in transactions non compliance transactions execution
          - System and operational implications

      - title: Risk Rating
        options:
          - Critical
          - High
          - Medium
          - Low
        criteria:
          - transactions non compliance violation severity
          - transactions non compliance likelihood
          - Control effectiveness
          - Potential system impact

      - title: Management Action
        format: bullet_points
        components:
          - Required corrective actions
          - User responsibility assignments
          - Success criteria for process improvement

  writing_guidelines:
    style:
      - Use passive voice
      - Avoid personal pronouns
      - No subjective language
      - Plain English
      - Define abbreviations first

    formatting:
      - Consistent bullet point structure
      - Proper comma usage
      - Single transition words
      - Parallel structure in lists

    content:
      - Focus on change management process risks
      - Clear root cause identification
      - Impact assessment of non-compliant changes
      - Recommended compensating controls
      - Specific time frame specification


compile_audit_report:
    description: Compile all findings from findings folder into comprehensive audit report
    agent: audit_report_writer
    priority: 2
    input_path: findings/*.md
    output_file: DraftAuditReport.md
    expected_output: A comprehensive audit report with structured sections
    report_structure:
        sections:
            - title: Executive Summary
              required: true
              components:
                - title: Critical Issues
                  content: Aggregated list of all findings with Critical risk rating
                  format: bullet_points
                
                - title: High Risk Issues
                  content: Aggregated list of all findings with High risk rating
                  format: bullet_points
                
                - title: Key Findings Overview
                  content: Summary of all major observations
                  format: bullet_points
                
                - title: Risk Profile
                  content: Distribution of risk ratings across findings
                  format: table
                  columns:
                    - Risk Rating
                    - Count
                    - Percentage
            
            - title: Detailed Observations
              required: true
              structure: per_finding
              source: findings_folder
              sections_to_include:
                - Observation
                - Observation Details
                - Observation Risks
                - Risk Rating (Critical / High / Medium / Low)
                - Management Action
              formatting:
                - Preserve original section hierarchy
                - Include the found discrepancies 
                - Maintain bullet point structure
                - Keep original risk ratings
                - Include source file reference
    
    compilation_rules:
        finding_selection:
            - Include all .md files from findings folder
            - Parse headers using markdown structure
            - Preserve original formatting within sections
            - Include the found discrepancies 
        
        executive_summary:
            - Aggregate all Critical and High risks first
            - Summarize key points from each finding
            - Calculate risk distribution statistics
            - Present trends and patterns
        
        detailed_findings:
            - Group by finding source
            - Maintain original section order
            - Preserve all formatting and lists
            - Include full observation details
    
    quality_control:
        checks:
            - All required sections present
            - Consistent risk rating usage
            - Complete management actions
            - Proper section hierarchy
            - Evidence documentation
        
        formatting:
            - Consistent header levels
            - Proper bullet point structure
            - Clear section breaks
            - Professional layout
            - Proper citation of source findings
    
    writing_standards:
        style:
            - Professional tone
            - Objective language
            - Clear and concise
            - Risk-focused approach
        
        content:
            - Evidence-based findings
            - Clear impact analysis
            - Practical recommendations
            - Measurable outcomes
            - Source traceability


