review_logical_access:
    description: Compare system access levels against authorized access matrix
    agent: logical_access_reviewer
    priority: 1
    expected_output: A markdown file containing access-related findings with title, background, discrepancies, and user feedback section


compile_audit_report:
    description: Compile all findings into comprehensive audit report
    agent: audit_report_writer
    priority: 2
    outputs: final_audit_report.md
    expected_output: A comprehensive audit report with executive summaries, detailed findings, risk ratings, and management actions. Add A section for entire logical access risk rating.
