review_logical_access:
    description: Compare system access levels against authorized access matrix
    agent: logical_access_reviewer
    priority: 1
    expected_output: A markdown file containing access-related findings
    output_structure:
        sections:
            - title: Observation 
              requirements:
                - Subject-focused and concise
                - Non-negative phrasing
                - Clear without technical jargon
            - title: Observation Details
              format: bullet_points
              requirements:
                - Direct and concise points that explains the noted discrepancies.
                - Logical flow in main and sub-bullets
                - No background information
                - Clear timeline and scope
                - Evidence-based findings
            - title: Risk Assessment
              components:
                - Identified risks
                - Impact analysis
                - Control gaps
                - System implications
            - title: Risk Rating
              options:
                - Critical
                - High
                - Medium
                - Low
              criteria:
                - Impact severity
                - Likelihood
                - Control effectiveness
            - title: Management Action
              format: bullet_points
              components:
                - Required actions
                - Responsibilities
                - Success criteria
    writing_guidelines:
        style:
            - Use passive voice
            - Avoid personal pronouns
            - No subjective language
            - Plain English
            - Define abbreviations first
        formatting:
            - Consistent bullet point structure
            - Proper comma usage
            - Single transition words
            - Parallel structure in lists
        content:
            - Focus on risk-based observations
            - Clear root cause identification
            - Impact assessment
            - Compensating controls
            - Time frame specification

review_transaction_limits:
    description: Analyze transaction approvals against authorized limits
    agent: limit_reviewer
    priority: 1
    expected_output: A markdown file containing limit-related findings
    output_structure:
        sections:
            - title: Observation Title
              requirements:
                - Subject-focused and concise
                - Non-negative phrasing
                - Clear without technical jargon
            - title: Observation Details
              format: bullet_points
              requirements:
                - Direct and concise points that explains the noted discrepancies.
                - Logical flow in main and sub-bullets
                - No background information
                - Clear timeline and scope
                - Evidence-based findings
            - title: Risk Assessment
              components:
                - Identified risks
                - Impact analysis
                - Control gaps
                - System implications
            - title: Risk Rating
              options:
                - Critical
                - High
                - Medium
                - Low
              criteria:
                - Impact severity
                - Likelihood
                - Control effectiveness
            - title: Management Action
              format: bullet_points
              components:
                - Required actions
                - Timeline
                - Responsibilities
                - Success criteria
    writing_guidelines:
        style:
            - Use passive voice
            - Avoid personal pronouns
            - No subjective language
            - Plain English
            - Define abbreviations first
        formatting:
            - Consistent bullet point structure
            - Proper comma usage
            - Single transition words
            - Parallel structure in lists
        content:
            - Focus on risk-based observations
            - Clear root cause identification
            - Impact assessment
            - Compensating controls
            - Time frame specification


review_transactions:
    description: Analyze transactions for policy violations
    agent: transaction_reviewer
    priority: 1
    expected_output: A markdown file containing transaction-related findings with title, background, discrepancies, and user feedback section

review_audit_trail:
    description: Compare system changes against change tickets
    agent: audit_trail_reviewer
    priority: 1
    expected_output: A markdown file containing audit trail-related findings with title, background, discrepancies, and user feedback section












compile_audit_report:
    description: Compile all findings into comprehensive audit report
    agent: audit_report_writer
    priority: 2
    outputs: final_audit_report.md
    expected_output: A comprehensive audit report with structured sections
    report_structure:
        sections:
            - title: Executive Summary for the overall observations
              components:
                - Overall risk assessment
                - Key findings summary
                - Critical issues highlight
                - Impact overview
            - title: Detailed Observations
              format: per_finding (repeat for every observation)
              components:
                - Observation title
                - Observation details
                - Risk assessment
                - Risk rating
                - Management action            
    quality_control:
        checks:
            - Direct and concise points that explains the noted discrepancies.
            - Grammar and flow
            - Consistency in risk ratings
            - Completeness of observations
            - Action item practicality
            - Evidence documentation
        formatting:
            - Proper section hierarchy
            - Consistent bullet styling
            - Clear visual breaks
            - Professional layout
    writing_standards:
        style:
            - Professional tone
            - Objective language
            - Clear and concise
            - Risk-focused approach
        content:
            - Evidence-based findings
            - Clear impact analysis
            - Practical recommendations
            - Measurable outcomes
